import 'package:flutter/material.dart';
import '../../services/auth_service.dart';
import '../../widgets/primary_button.dart';
import '../../widgets/unigo_logo.dart';

class AuthScreen extends StatefulWidget { const AuthScreen({super.key}); @override State<AuthScreen> createState() => _AuthScreenState(); }
class _AuthScreenState extends State<AuthScreen> { final email=TextEditingController(), password=TextEditingController(), name=TextEditingController(), city=TextEditingController(); bool register=false, busy=false, obscure=true; final auth=AuthService();
Future<void> submit() async { setState(()=>busy=true); try { if(register) { await auth.register(email.text,password.text,name.text,city:city.text); } else { await auth.signIn(email.text,password.text); } } catch(e) { if(mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString().replaceFirst('Exception: ','')))); } finally { if(mounted)setState(()=>busy=false); } }
@override Widget build(BuildContext context) => Scaffold(body: SafeArea(child: Center(child: SingleChildScrollView(padding: const EdgeInsets.all(28), child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 460), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Center(child: UnigoLogo(size: 68)), const SizedBox(height: 28), Text(register?'UNIGO’ya katıl':'Tekrar hoş geldin',style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.w800)), const SizedBox(height: 8), Text(register?'Şehrindeki ulaşım seçeneklerini tek yerde keşfet.':'Hızlıca devam et ve yakınındaki seçenekleri gör.'), const SizedBox(height: 28), if(register) ...[TextField(controller:name,decoration:const InputDecoration(labelText:'Ad Soyad')),const SizedBox(height:12),TextField(controller:city,decoration:const InputDecoration(labelText:'Şehir')),const SizedBox(height:12)], TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'E-posta')), const SizedBox(height:12), TextField(controller:password,obscureText:obscure,decoration:InputDecoration(labelText:'Şifre',suffixIcon:IconButton(onPressed:()=>setState(()=>obscure=!obscure),icon:Icon(obscure?Icons.visibility_outlined:Icons.visibility_off_outlined)))), const SizedBox(height:22), PrimaryButton(label:busy?'Bekleyin...':register?'Kayıt ol':'Giriş yap',onPressed:busy?null:submit), const SizedBox(height:12), OutlinedButton.icon(onPressed:busy?null:()=>auth.google(),icon:const Icon(Icons.g_mobiledata_rounded),label:const Text('Google ile devam et'),style:OutlinedButton.styleFrom(minimumSize:const Size.fromHeight(52),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18)))), const SizedBox(height:18), Center(child:TextButton(onPressed:()=>setState(()=>register=!register),child:Text(register?'Zaten hesabım var':'Yeni hesap oluştur')))]))))));
}
